version: '3.8'
services:      
  postgres:
    image: postgres:12.3
    network_mode: bridge
    container_name: postgres
    environment:
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=sa
      - POSTGRES_DB=socialb
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    ports:
      - "5432:5432"
    volumes:
      - ./pg-data:/var/lib/postgresql/data

  restful-webservices:
    image: abhinavkmishra14/restful-webservices:1.0-SNAPSHOT
    network_mode: bridge
    container_name: restful-webservices
    environment:
      JAVA_OPTS: "
                -Dserver.servlet.contextPath=/rwsspringboot
                -Dserver.port=8181
                -Dlogging.level.web=debug
                -Dspring.messages.basename=messages
                -Dmanagement.endpoints.web.exposure.include=*
                -Dspring.h2.console.enabled=false
                -Dspring.datasource.url=jdbc:postgresql://postgres:5432/socialb
                -Dspring.datasource.driver-class-name=org.postgresql.Driver
                -Dspring.datasource.username=sa
                -Dspring.datasource.password=sa
                -Dspring.jpa.hibernate.ddl-auto=update
                -Dspring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
                "
    ports:
      - "8181:8181"
    volumes:
      - ./logs:/logs
    depends_on:
      - postgres
    links:
      - postgres