version: '3.8'
services:      
  postgres:
    image: postgres:12.3
    network_mode: bridge
    container_name: postgres
    environment:
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=sa
      - POSTGRES_DB=currexec
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    ports:
      - "5432:5432"
    volumes:
      - ./pg-data:/var/lib/postgresql/data

  spring-cloud-config-server:
    image: abhinavkmishra14/spring-cloud-config-server:1.0-SNAPSHOT
    network_mode: bridge
    container_name: spring-cloud-config-server
    environment:
      JAVA_OPTS: "
                -Dserver.port=8888
                -Dlogging.level.web=debug
                -Dspring.cloud.config.server.git.uri=https://github.com/abhinavmishra14/spring-microservices-config-repo
                -Dspring.cloud.config.server.git.clone-on-start=true
                -Dspring.cloud.config.server.git.skip-ssl-validation=true
                -Dspring.cloud.config.server.git.search-paths=limits-service
                -Dspring.cloud.config.server.git.force-pull=true
                -Dspring.cloud.config.server.git.basedir=/config-repoo
                "
    ports:
      - "8888:8888"
    volumes:
      - ./config-repo:/config-repo
      
  netflix-eureka-naming-server:
    image: abhinavkmishra14/netflix-eureka-naming-server:1.0-SNAPSHOT
    network_mode: bridge
    container_name: netflix-eureka-naming-server
    environment:
      JAVA_OPTS: "
                -Dlogging.level.web=debug
                -Dserver.port=8761
                -Deureka.client.register-with-eureka=false
                -Deureka.client.fetch-registry=false
                "
    ports:
      - "8761:8761"
    volumes:
      - ./logs:/logs
      
  netflix-zuul-api-gateway-server:
    image: abhinavkmishra14/netflix-zuul-api-gateway-server:1.0-SNAPSHOT
    network_mode: bridge
    container_name: netflix-zuul-api-gateway-server
    environment:
      JAVA_OPTS: "
                -Dlogging.level.web=debug
                -Dserver.port=8765
                -Deureka.client.service-url.default-zone=http://netflix-eureka-naming-server:8761/eureka
                "
    ports:
      - "8765:8765"
    volumes:
      - ./logs:/logs
    depends_on:
      - netflix-eureka-naming-server
      - zipkin
    links:
      - netflix-eureka-naming-server
      - zipkin
      
  limits-service:
    image: abhinavkmishra14/limits-service:1.0-SNAPSHOT
    network_mode: bridge
    container_name: limits-service
    environment:
      JAVA_OPTS: "
                -Dlogging.level.web=debug
                -Dserver.port=8080
                -Deureka.client.service-url.default-zone=http://netflix-eureka-naming-server:8761/eureka
                -Dspring.cloud.config.uri=http://spring-cloud-config-server:8888
                -Dspring.profiles.active=qa
                -Dmanagement.endpoints.web.exposure.include=*
                "
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/logs
    depends_on:
      - netflix-eureka-naming-server
      - spring-cloud-config-server
      - zipkin
    links:
      - netflix-eureka-naming-server
      - spring-cloud-config-server
      - zipkin
      
  currency-exchange-service:
    image: abhinavkmishra14/currency-exchange-service:1.0-SNAPSHOT
    network_mode: bridge
    container_name: currency-exchange-service
    environment:
      JAVA_OPTS: "
                -Dlogging.level.web=debug
                -Dserver.port=8000
                -Deureka.client.service-url.default-zone=http://netflix-eureka-naming-server:8761/eureka
                -Dspring.h2.console.enabled=false
                -Dspring.datasource.url=jdbc:postgresql://postgres:5432/currexec
                -Dspring.datasource.driver-class-name=org.postgresql.Driver
                -Dspring.datasource.username=sa
                -Dspring.datasource.password=sa
                -Dspring.jpa.hibernate.ddl-auto=update
                -Dspring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
                -Dexchange.rate.fallback.uri=https://api.exchangeratesapi.io/latest?base={0}&symbols={1}
                "
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/logs
    depends_on:
      - postgres
      - netflix-eureka-naming-server
      - zipkin
    links:
      - postgres
      - netflix-eureka-naming-server
      - zipkin
      
  currency-conversion-service:
    image: abhinavkmishra14/currency-conversion-service:1.0-SNAPSHOT
    network_mode: bridge
    container_name: currency-conversion-service
    environment:
      JAVA_OPTS: "
                -Dlogging.level.web=debug
                -Dserver.port=8100
                -Deureka.client.service-url.default-zone=http://netflix-eureka-naming-server:8761/eureka
                -Dexchange.rate.fallback.uri=https://api.exchangeratesapi.io/latest?base={0}&symbols={1}
                "
    ports:
      - "8100:8100"
    volumes:
      - ./logs:/logs
    depends_on:
      - netflix-eureka-naming-server
      - zipkin
    links:
      - netflix-eureka-naming-server
      - zipkin
  
  rabbitmq:
    image: rabbitmq:3.7.6-management
    network_mode: bridge
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - "TZ=@timezone@"

  zipkin:
    image: openzipkin/zipkin:2.10.2
    network_mode: bridge
    container_name: zipkin
    depends_on:
      - rabbitmq
    ports:
      - "9411:9411"
    environment:
      - "TZ=@timezone@"
      - "RABBIT_URI=amqp://guest:guest@rabbitmq:5672"