version: '3.8'
services: 
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:1567
      
  zipkin:
    image: openzipkin/zipkin:2.22
    #For swarm mode, use deploy and its subkeys to control the restart behavior:
    #deploy:
    #  restart_policy:
    #    condition: on-failure 
    #    delay: 5s
    #    max_attempts: 5
    #    window: 120s
    container_name: zipkin
    hostname: zipkin
    depends_on:
      - rabbitmq
    restart: on-failure:5 #Restart the zipkin container again if it failed to connect to rabbitmq and exited, repeat until rabbitmq is up and running, max attempt is 5
    ports:
      - "9410:9410"
      - "9411:9411"
    environment:
      - "RABBIT_URI=amqp://rabbitmq"
      
  spring-cloud-config-server:
    image: abhinavkmishra14/spring-cloud-config-server:1.0-SNAPSHOT
    container_name: spring-cloud-config-server
    hostname: spring-cloud-config-server
    environment:
      JAVA_OPTS: "
                -Dserver.port=8888
                -Dspring.application.name=spring-cloud-config-server
                -Dlogging.level.web=debug
                -Dspring.cloud.config.server.git.uri=https://github.com/abhinavmishra14/spring-microservices-config-repo.git
                -Dspring.cloud.config.server.git.clone-on-start=false
                -Dspring.cloud.config.server.git.search-paths=limits-service
                -Dspring.cloud.config.server.git.force-pull=true
                -Dspring.rabbitmq.host=rabbitmq
                -Dspring.rabbitmq.port=5672
                "
    ports:
      - "8888:8888"
    depends_on:
      - rabbitmq
      - zipkin
    volumes:
      - ./logs:/logs
      
  netflix-eureka-naming-server:
    image: abhinavkmishra14/netflix-eureka-naming-server:1.0-SNAPSHOT
    container_name: netflix-eureka-naming-server
    hostname: netflix-eureka-naming-server
    environment:
      JAVA_OPTS: "
                -Dlogging.level.web=debug
                -Dspring.application.name=netflix-eureka-naming-server
                -Dserver.port=8761
                -Deureka.client.register-with-eureka=false
                -Deureka.client.fetch-registry=false
                "
    ports:
      - "8761:8761"
    volumes:
      - ./logs:/logs
